[package]
name = "pid_opt"
version = "0.1.0"
edition = "2024"

[dependencies]
aule = { git = "https://github.com/matheuswhite/aule-rs.git" }
derive_typst_intoval = "0.5.0"
image = "0.25.8"
rand = "0.9.2"
typst = "0.13.1"
typst-as-lib = "0.14.4"
typst-pdf = "0.13.1"
